version: '3.1'

services:

  db:
    image: mysql
    container_name: gameking-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: gameking

  adminer:
    image: adminer
    container_name: gameking-adminer
    restart: always
    ports:
      - 8080:8080

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2-nginx
    container_name: gameking-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - db
      - adminer
